# Generated by Django 6.0.6 on 2026-06-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('what', models.TextField()),
                ('where', models.CharField(choices=[('office', 'Office'), ('lounge', 'Lounge'), ('parkinglot', 'Parkinglot'), ('workspace1', 'WorkSpace1'), ('workspace2', 'WorkSpace2'), ('workspace3', 'WorkSpace3')])),
                ('reason', models.TextField()),
            ],
        ),
    ]
