# Generated by Django 6.0.6 on 2026-06-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportform',
            name='where',
            field=models.CharField(choices=[('office', 'Office'), ('lounge', 'Lounge'), ('parkinglot', 'Parking lot'), ('workspace1', 'WorkSpace1'), ('workspace2', 'WorkSpace2'), ('workspace3', 'WorkSpace3')]),
        ),
    ]
