# Generated by Django 6.0.6 on 2026-06-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_reportform_where'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('what', models.TextField()),
                ('where', models.CharField(choices=[('office', 'Office'), ('lounge', 'Lounge'), ('parkinglot', 'Parking lot'), ('workspace1', 'WorkSpace1'), ('workspace2', 'WorkSpace2'), ('workspace3', 'WorkSpace3')], max_length=15)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ReportForm',
        ),
    ]
